name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - jupyterlab=4.0.7
  - ipywidgets=8.1.1
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.3.1
  - ydata-profiling=4.6.0
  - protobuf=3.20.0
  - pydantic=1.10.13
  - pip:
      - wandb==0.10.31