name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - protobuf=3.20.0
  - cloudpickle=3.0.0
  - pip:
      - wandb==0.10.21
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
